- name: Install Nginx
  hosts: web_servers
  become: true

  tasks:
    # - name: Update package cache
    #   apt:
    #     update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: absent